### ISSUE TITLE
ERROR while running PotreeConverter and input data

### ISSUE THREAD

**Issue by dasha-5555-5** [qdnguyen/PotreeConvertor4Itowns#1]
Hello! I have been tried to build and run modified PotreeConverter and got this ERROR: boost::bad_any_cast: failed conversion using boost::any_cast. I haven't any idea to fix this problem. I just trien to convert my 3d model to absolute coordinate system and then visualize it by cesium. Can anyone help me?

**Comment by qdnguyen** [comment]
it seem to be a problem with boost, but it works for my case, do you have a data set to test? Do attention that i have modified only ply reader, if you store your data in other format, it may not works!

In addition, what is your referentiel? for my case, i convert my data from lambert93 to wgs84, you may need to modify the code if your data are not in lambert93.

**Comment by qdnguyen** [comment]
ok, i have time to take a look on it, it's because of null value of projection, you need to specify a value for --projection when you run the programe.
